"""
debug_external_decryption.py

Diagnostic script to debug why external_file_decryption_properties method is not available.

- mostly autogenerated.
"""

import sys
import traceback
import pyarrow.parquet.encryption as ppe


def debug_crypto_factory():
    """Debug the CryptoFactory class and its methods."""
    print("🔍 Debugging CryptoFactory class...")
    
    try:
        # Create a simple KMS client factory
        def simple_kms_factory(config):
            class SimpleClient(ppe.KmsClient):
                def __init__(self, config):
                    ppe.KmsClient.__init__(self)
                def wrap_key(self, key_bytes, master_key_identifier):
                    return key_bytes
                def unwrap_key(self, wrapped_key, master_key_identifier):
                    return wrapped_key
            return SimpleClient(config)
        
        # Create crypto factory
        crypto_factory = ppe.CryptoFactory(simple_kms_factory)
        print(f"✅ CryptoFactory created successfully")
        print(f"   Type: {type(crypto_factory)}")
        
        # Get all methods
        methods = [m for m in dir(crypto_factory) if not m.startswith('_')]
        print(f"   Available methods: {methods}")
        
        # Check for specific methods
        specific_methods = [
            'external_file_encryption_properties',
            'external_file_decryption_properties',
            'file_encryption_properties',
            'file_decryption_properties'
        ]
        
        print(f"\n📋 Checking specific methods:")
        for method in specific_methods:
            if hasattr(crypto_factory, method):
                print(f"   ✅ {method} - AVAILABLE")
                # Try to get method info
                try:
                    method_obj = getattr(crypto_factory, method)
                    print(f"      Type: {type(method_obj)}")
                    print(f"      Callable: {callable(method_obj)}")
                except Exception as e:
                    print(f"      Error getting method info: {e}")
            else:
                print(f"   ❌ {method} - NOT AVAILABLE")
        
        return crypto_factory
        
    except Exception as e:
        print(f"❌ Error creating CryptoFactory: {e}")
        print(f"   Error type: {type(e).__name__}")
        traceback.print_exc()
        return None


def debug_imports():
    """Debug the imports and module structure."""
    print("\n🔍 Debugging imports...")
    
    try:
        print(f"✅ pyarrow.parquet.encryption imported successfully")
        print(f"   Module: {ppe}")
        print(f"   Module type: {type(ppe)}")
        
        # Check what's available in the module
        module_attrs = [attr for attr in dir(ppe) if not attr.startswith('_')]
        print(f"   Available attributes: {module_attrs}")
        
        # Check specific classes
        classes_to_check = [
            'CryptoFactory',
            'ExternalEncryptionConfiguration',
            'ExternalConnectionConfiguration',
            'DecryptionConfiguration',
            'KmsConnectionConfig'
        ]
        
        print(f"\n📋 Checking specific classes:")
        for class_name in classes_to_check:
            if hasattr(ppe, class_name):
                print(f"   ✅ {class_name} - AVAILABLE")
                class_obj = getattr(ppe, class_name)
                print(f"      Type: {type(class_obj)}")
            else:
                print(f"   ❌ {class_name} - NOT AVAILABLE")
        
    except Exception as e:
        print(f"❌ Error with imports: {e}")
        print(f"   Error type: {type(e).__name__}")
        traceback.print_exc()


def test_method_call(crypto_factory):
    """Test calling the method if it exists."""
    if crypto_factory is None:
        return
    
    print(f"\n🔍 Testing method call...")
    
    try:
        # Check if method exists
        if not hasattr(crypto_factory, 'external_file_decryption_properties'):
            print("❌ Method external_file_decryption_properties not found")
            return
        
        print("✅ Method found, attempting to call...")
        
        # Create test configurations
        kms_config = ppe.KmsConnectionConfig(
            custom_kms_conf={"test": "value"}
        )
        
        decryption_config = ppe.DecryptionConfiguration(
            cache_lifetime=300.0
        )
        
        external_encryption_config = ppe.ExternalEncryptionConfiguration(
            user_id="test",
            ext_column_keys='{"key": "value"}',
            app_context='{"context": "test"}'
        )
        
        external_connection_config = ppe.ExternalConnectionConfiguration(
            config_path="/test/path"
        )
        
        print("✅ Configurations created")
        
        # Try to call the method
        result = crypto_factory.external_file_decryption_properties(
            kms_config,
            decryption_config,
            external_encryption_config,
            external_connection_config
        )
        
        print(f"✅ Method call successful!")
        print(f"   Result type: {type(result)}")
        print(f"   Result: {result}")
        
    except Exception as e:
        print(f"❌ Error calling method: {e}")
        print(f"   Error type: {type(e).__name__}")
        traceback.print_exc()


def check_pyarrow_version():
    """Check PyArrow version and build information."""
    print(f"\n🔍 Checking PyArrow version...")
    
    try:
        import pyarrow as pa
        print(f"✅ PyArrow version: {pa.__version__}")
        
        # Try to get build info
        try:
            build_info = pa.get_build_info()
            print(f"   Build info: {build_info}")
        except:
            print("   Build info not available")
            
    except Exception as e:
        print(f"❌ Error getting PyArrow version: {e}")


def main():
    """Run all diagnostics."""
    print("🔧 External Decryption Bindings Diagnostic")
    print("=" * 50)
    
    # Check PyArrow version
    check_pyarrow_version()
    
    # Debug imports
    debug_imports()
    
    # Debug CryptoFactory
    crypto_factory = debug_crypto_factory()
    
    # Test method call
    test_method_call(crypto_factory)
    
    print(f"\n" + "=" * 50)
    print("DIAGNOSTIC COMPLETE")
    print("=" * 50)
    
    if crypto_factory and hasattr(crypto_factory, 'external_file_decryption_properties'):
        print("🎉 The method should be available!")
    else:
        print("💥 The method is NOT available. Check the output above for details.")
        print("\nPossible issues:")
        print("1. PyArrow was not rebuilt after adding the bindings")
        print("2. There's a compilation error in the C++ code")
        print("3. The method name is different than expected")
        print("4. There's an import issue")


if __name__ == "__main__":
    main()
