"""
simple_external_decryption_test.py

Simple test script to verify the new external decryption bindings work correctly.
This script focuses specifically on testing the new API methods without the complexity
of the full encrypt/decrypt workflow.

- mostly autogenerated.

@author assistant
"""

import datetime
import pyarrow.parquet.encryption as ppe


class SimpleKmsClient(ppe.KmsClient):
    """Simple KMS client for testing."""
    
    def __init__(self, kms_connection_config):
        ppe.KmsClient.__init__(self)
        self.master_keys_map = kms_connection_config.custom_kms_conf
    
    def wrap_key(self, key_bytes, master_key_identifier):
        # Simple implementation for testing
        return key_bytes
    
    def unwrap_key(self, wrapped_key, master_key_identifier):
        # Simple implementation for testing
        return wrapped_key


def kms_client_factory(kms_connection_config):
    return SimpleKmsClient(kms_connection_config)


def test_binding_availability():
    """Test that the new binding method is available."""
    print("🔍 Testing binding availability...")
    
    try:
        crypto_factory = ppe.CryptoFactory(kms_client_factory)
        
        # Check if the method exists
        if hasattr(crypto_factory, 'external_file_decryption_properties'):
            print("✅ external_file_decryption_properties method is available")
            return True
        else:
            print("❌ external_file_decryption_properties method is NOT available")
            print(f"Available methods: {[m for m in dir(crypto_factory) if not m.startswith('_')]}")
            return False
            
    except Exception as e:
        print(f"❌ Error checking binding availability: {e}")
        return False


def test_method_signature():
    """Test that the method has the correct signature."""
    print("\n🔍 Testing method signature...")
    
    try:
        crypto_factory = ppe.CryptoFactory(kms_client_factory)
        method = crypto_factory.external_file_decryption_properties
        
        # Check if it's callable
        if callable(method):
            print("✅ Method is callable")
            
            # Try to get signature info
            import inspect
            try:
                sig = inspect.signature(method)
                print(f"✅ Method signature: {sig}")
                return True
            except Exception as e:
                print(f"⚠️  Could not inspect signature: {e}")
                return True  # Still callable, so probably OK
        else:
            print("❌ Method is not callable")
            return False
            
    except Exception as e:
        print(f"❌ Error checking method signature: {e}")
        return False


def test_configuration_creation():
    """Test that all required configuration objects can be created."""
    print("\n🔍 Testing configuration creation...")
    
    try:
        # Test KMS connection config
        kms_config = ppe.KmsConnectionConfig(
            custom_kms_conf={"test_key": "test_value"}
        )
        print("✅ KmsConnectionConfig created")
        
        # Test decryption config
        decryption_config = ppe.DecryptionConfiguration(
            cache_lifetime=datetime.timedelta(minutes=5)
        )
        print("✅ DecryptionConfiguration created")
        
        # Test external encryption config
        external_encryption_config = ppe.ExternalEncryptionConfiguration(
            user_id="test_user",
            ext_column_keys='{"keyId": "test123"}',
            app_context='{"test": "context"}'
        )
        print("✅ ExternalEncryptionConfiguration created")
        
        # Test external connection config
        external_connection_config = ppe.ExternalConnectionConfiguration(
            config_path="/test/path"
        )
        print("✅ ExternalConnectionConfiguration created")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating configurations: {e}")
        return False


def test_method_call():
    """Test that the method can be called with valid parameters."""
    print("\n🔍 Testing method call...")
    
    try:
        # Create all required configurations
        kms_config = ppe.KmsConnectionConfig(
            custom_kms_conf={"test_key": "test_value"}
        )
        
        decryption_config = ppe.DecryptionConfiguration(
            cache_lifetime=datetime.timedelta(minutes=5)
        )
        
        external_encryption_config = ppe.ExternalEncryptionConfiguration(
            user_id="test_user",
            ext_column_keys='{"keyId": "test123"}',
            app_context='{"test": "context"}'
        )
        
        external_connection_config = ppe.ExternalConnectionConfiguration(
            config_path="/test/path"
        )
        
        # Create crypto factory
        crypto_factory = ppe.CryptoFactory(kms_client_factory)
        
        # Call the method
        print("   Calling external_file_decryption_properties...")
        result = crypto_factory.external_file_decryption_properties(
            kms_config,
            decryption_config,
            external_encryption_config,
            external_connection_config
        )
        
        print(f"✅ Method call successful!")
        print(f"   Result type: {type(result)}")
        print(f"   Result: {result}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error calling method: {e}")
        print(f"   Error type: {type(e).__name__}")
        return False


def test_regular_decryption_comparison():
    """Test that regular decryption still works for comparison."""
    print("\n🔍 Testing regular decryption for comparison...")
    
    try:
        kms_config = ppe.KmsConnectionConfig(
            custom_kms_conf={"test_key": "test_value"}
        )
        
        decryption_config = ppe.DecryptionConfiguration(
            cache_lifetime=datetime.timedelta(minutes=5)
        )
        
        crypto_factory = ppe.CryptoFactory(kms_client_factory)
        
        result = crypto_factory.file_decryption_properties(
            kms_config,
            decryption_config
        )
        
        print(f"✅ Regular decryption method works!")
        print(f"   Result type: {type(result)}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error with regular decryption: {e}")
        return False


def main():
    """Run all tests."""
    print("🧪 Simple External Decryption Bindings Test")
    print("=" * 50)
    
    tests = [
        ("Binding Availability", test_binding_availability),
        ("Method Signature", test_method_signature),
        ("Configuration Creation", test_configuration_creation),
        ("Method Call", test_method_call),
        ("Regular Decryption Comparison", test_regular_decryption_comparison),
    ]
    
    results = []
    
    for test_name, test_func in tests:
        print(f"\n📋 Running: {test_name}")
        print("-" * 30)
        
        try:
            result = test_func()
            results.append((test_name, result))
        except Exception as e:
            print(f"💥 Test failed with exception: {e}")
            results.append((test_name, False))
    
    # Summary
    print("\n" + "=" * 50)
    print("TEST SUMMARY")
    print("=" * 50)
    
    passed = 0
    total = len(results)
    
    for test_name, result in results:
        status = "✅ PASS" if result else "❌ FAIL"
        print(f"{status} {test_name}")
        if result:
            passed += 1
    
    print(f"\nResults: {passed}/{total} tests passed")
    
    if passed == total:
        print("\n🎉 All tests passed! The external decryption bindings are working correctly.")
        return True
    else:
        print(f"\n💥 {total - passed} test(s) failed. Check the output above for details.")
        return False


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
